services:
  thream-website:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: 'thream-website'
    build:
      context: './'
    ports:
      - '${PORT-3000}:${PORT-3000}'
    environment:
      PORT: ${PORT-3000}
    env_file: './.env'
