version: '3.0'
services:
  thream-website:
    container_name: ${COMPOSE_PROJECT_NAME}
    build:
      context: './'
      dockerfile: './Dockerfile'
    ports:
      - '${PORT}:${PORT}'
    environment:
      PORT: ${PORT}
    volumes:
      - './:/website'
