services:
  thream-website:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: 'thream-website'
    build:
      context: './'
    ports:
      - '${PORT}:${PORT}'
    environment:
      PORT: ${PORT}
    env_file: './.env'
